dependencies:
  # Chainlink
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
  # OpenZeppelin
  - OpenZeppelin/openzeppelin-contracts@4.3.0
compiler:
  solc:
    version: 0.8.0
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.3.0'
dotenv:
  .env
network:
  goerli:
    eth_usd_price_feed: '0x694AA1769357215DE4FAC081bf1f309aDC325306'
    verify: True
  development:
    verify: False
wallets:
  from_key: ${PRIVATE_KEY}